### PR TITLE
Updates for recent ruby versions (removes warnings in 1.9.3 and above) as well as activesupport 3.2+

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by jeremy** [comment]
Cool. You'll need to bump the activesupport gem dependency to the first version that supports `class_attribute`, too.

**Comment by doudou** [comment]
Weird ... I thought I did. I will update the MR.

2013/12/2 Jeremy Kemper notifications@github.com

**Comment by doudou** [comment]
Any chance this gets merged ?

**Comment by doudou** [comment]
Oh ... f... Realized that I did a PR on my master and that I went on developing there. The commits have nothing to do with the PR. I'm learning to use github's PR properly, sorry for that.

**Comment by doudou** [comment]
Stopped using rubygen, replaced it by thor's gen mechanisms.

**Pull request closed without merging**
